quarkus:
  swagger-ui:
    always-include: true
  http:
    port: 8080
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jdbc:
      url: ${DB_URL_RW}
    ro:
      db-kind: postgresql
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      jdbc:
        url: ${DB_URL_RO}
  fault-tolerance:
    bulkhead:
      max-concurrent-calls: 20
      waiting-task-queue: 40
  hibernate-orm:
    log:
      sql: false
  log:
    category:
      "org.hibernate":
        level: WARN

  # Configurações do Flyway (Migrações)
  flyway:
    migrate-at-start: true
    repair-at-start: true
    baseline-on-migrate: true
    out-of-order: true
    ignore-missing-migrations: true
  # Configuração da extensão de Segurança (SmallRye JWT)
  smallrye-jwt:
    enabled: true

smallrye:
  jwt:
    sign:
      key:
        location: "privateKey.pem"
    verify:
      issuer: "oficina-api-interna"
      key:
        location: "publicKey.pem"