quarkus:
  swagger-ui:
    always-include: true
  http:
    port: 8080

  # Configurações do Banco de Dados (PostgreSQL)
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/oficina

  # Configurações do Hibernate (Desativado para o Flyway assumir o controle)
  hibernate-orm:
    log:
      sql: true

  # Configurações do Flyway (Migrações)
  flyway:
    migrate-at-start: true
    repair-at-start: true
    baseline-on-migrate: true
    out-of-order: true
    ignore-missing-migrations: true
  # Configuração da extensão de Segurança (SmallRye JWT)
  smallrye-jwt:
    enabled: true

smallrye:
  jwt:
    sign:
      key:
        location: "privateKey.pem"
    verify:
      issuer: "oficina-api-interna"
      key:
        location: "publicKey.pem"