# Não commitar valores reais aqui. Os placeholders ${...} são preenchidos via
# `envsubst` a partir de GitHub Secrets no job build-and-deploy do ci.yml antes
# do apply. Para aplicar manualmente (ex: local/Minikube), use kubectl create
# secret (mais seguro que envsubst sobre YAML — evita quebrar o parser se
# algum valor tiver caractere especial):
#   kubectl create secret generic oficina-db-app \
#     --from-literal=username=... --from-literal=password=... \
#     --from-literal=webhook-aprovacao-secret=... \
#     --from-literal=azure-storage-connection-string=... \
#     --from-literal=new-relic-license-key=... \
#     --dry-run=client -o yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: oficina-db-app
type: Opaque
stringData:
  username: ${DB_APP_USERNAME}
  password: ${DB_APP_PASSWORD}
  webhook-aprovacao-secret: ${WEBHOOK_APROVACAO_SECRET}
  azure-storage-connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
  new-relic-license-key: ${NEW_RELIC_LICENSE_KEY}
