apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: gateway
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: gateway
spec:
  type: ClusterIP
  selector:
    app: traefik
  ports:
    - name: dashboard
      protocol: TCP
      port: 8080
      targetPort: 8080
