CREATE TABLE USUARIO (
    id UUID PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    perfil VARCHAR(50) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    -- O BANCO REJEITA QUALQUER COISA FORA DESSA LISTA:
    CONSTRAINT chk_usuario_perfil CHECK (perfil IN ('ADMIN', 'MECANICO', 'ATENDENTE', 'CLIENTE'))
);