CREATE TABLE ORDEM_SERVICO (
    id UUID PRIMARY KEY,
    veiculo_id UUID NOT NULL,
    cliente_id UUID NOT NULL,
    status VARCHAR(50) NOT NULL,
    data_abertura TIMESTAMP NOT NULL,
    data_conclusao TIMESTAMP,
    valor_total DECIMAL(10, 2) DEFAULT 0.00,
    CONSTRAINT fk_os_veiculo FOREIGN KEY (veiculo_id) REFERENCES VEICULO(id),
    CONSTRAINT fk_os_cliente FOREIGN KEY (cliente_id) REFERENCES CLIENTE(id),
    CONSTRAINT chk_os_status CHECK (status IN ('EM_DIAGNOSTICO', 'AGUARDANDO_APROVACAO', 'EM_EXECUCAO', 'AGUARDANDO_PAGAMENTO', 'CONCLUIDA'))
);