ALTER TABLE ORDEM_DE_SERVICO DROP CONSTRAINT chk_os_status;

ALTER TABLE ORDEM_DE_SERVICO ADD CONSTRAINT chk_os_status CHECK (status IN (
    'ABERTA',
    'EM_DIAGNOSTICO',
    'ORCAMENTO',
    'AGUARDANDO_APROVACAO',
    'APROVADA',
    'REPROVADA',
    'REJEITADA',
    'EM_EXECUCAO',
    'AGUARDANDO_PAGAMENTO',
    'PAGA',
    'FINALIZADA',
    'ENTREGUE',
    'CANCELADA'
));
